### ISSUE TITLE
Right panel buttons hidden when Admin bar is shown

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#16]
I like to leave the Admin bar visible when in the Oxygen editor for easy access to all pages and templates and other custom links I keep in the bar. When it's visible, the 4 panels to switch views of the right sidebar and the save button are hidden.

<img width="1916" alt="Screen Shot 2021-07-03 at 4 27 45 PM" src="https://user-images.githubusercontent.com/13838253/124368971-aaa37980-dc1b-11eb-9017-fe790113df81.png">

**Comment by re-co** [comment]
Please disable Editior Enhancer! 
We are not testing plugin with other 3rd party plugins, we need resolve issues between oxygen and this plugin so we can do next step.

Goal is to find bugs between Oxygen and recoda-ws

**Comment by re-co** [comment]
Fixed in 0.9.0.
Implementation: added JS which check if oxygen topbar has offeset to top, if it has adds that value to CSS variable.
It should solve this and oxy toolbox bar problem.
