### ISSUE TITLE
"Hide" button is obscured

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#17]
It's hidden behind the Add button.

<img width="102" alt="Screen Shot 2021-07-02 at 6 06 04 PM" src="https://user-images.githubusercontent.com/13838253/124368988-d7579100-dc1b-11eb-9578-fb098714f4e6.png">

**Comment by re-co** [comment]
We don't  use hide/show.
Please read Wiki -> 1 Workflow 2x 

We have feature called Left and Right Panel Resizer under that feature. This feature gives you two ways of of hiding 

1. Double click to hide/show
2. Just drag to left edge of screen so we don't use some native feature if our are far more superior 

NOTE: It should not be even visible, I'll check CSS to set it to display none.
