### ISSUE TITLE
List of elements switches from 3 columns to 2 on hover

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#19]
When you first display the list of elements after clicking the +Add button, it shows them in 3 columns:
<img width="358" alt="Screen Shot 2021-07-03 at 4 32 06 PM" src="https://user-images.githubusercontent.com/13838253/124369046-619ff500-dc1c-11eb-85b9-d56085947d77.png">

But as soon as you hover over them, it switches to 2 columns:
<img width="358" alt="Screen Shot 2021-07-03 at 4 32 17 PM" src="https://user-images.githubusercontent.com/13838253/124369063-9c099200-dc1c-11eb-97a2-415f57f62dd8.png">

**Comment by re-co** [comment]
Please disable Editor Enhancer! 
We are not testing plugin with other 3rd party plugins, we need resolve issues between oxygen and this plugin so we can do next step.

Bug is not related to this plugin only, it happens because some EE feture
