### ISSUE TITLE
Locked classes are not shown in locked (red) colour

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#20]
I use Hydrogen Pack to lock classes. When locked. red is used rather than green to denote they are locked. The list of used classes does not use the red "locked" colour:
<img width="343" alt="Icon Button" src="https://user-images.githubusercontent.com/13838253/124369090-e3901e00-dc1c-11eb-86dd-cc055f96d1a6.png">

**Comment by re-co** [comment]
We are using blue for ID, green for class. Currently locked class highlighting is not supported.

Please disable hydrogen and 3rd party plugins when you test! 
We are not testing plugin with other 3rd party plugins, we need resolve issues between oxygen and this plugin so we can do next step.
First things first, hope you understand.

**Comment by AnInfiniteNumberofMonkeys** [comment]
Definitely can't disable Hydrogen pack...Oxygen is unusable without Copy & Paste. Note: this fix is as simple as adding the following CSS: 
div:not(.oxygen-active-select.oxygen-active-classes-select)>ul.oxygen-classes-dropdown li.oxygen-class-locked:nth-child(n+6) {
    border-left: 5px solid #EF5350;
}

**Comment by re-co** [comment]
Thanks on solution. 

Let my explain why I say disable 3rd party plugins

I have been developing this plugin on win 10 and firefox. It could have some weird things on different OS and browser, even I find every day some things that need tweaks.

I think right solution is to catch these core bugs so I can implement tweaks for.

So I am not suggesting that you don't use Swiss Knife/Hydogen/EE etc. in production, just in this case of testing purpose.

**Comment by re-co** [comment]
Added recoda indicator for locked class in 0.9,0
