### ISSUE TITLE
Bottom buttons don't work

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#22]
There are series of buttons across the bottom of the screen:
<img width="462" alt="Screen Shot 2021-07-03 at 4 43 30 PM" src="https://user-images.githubusercontent.com/13838253/124369187-e8090680-dc1d-11eb-9cce-23ccbdfda0c7.png">

**Launch new live server instance**: opens a new window with the frontend view of the current page. But why?
**Refresh live server instance**: causes the window that was launched to refresh. But why? It's easier to refresh the window with Ctrl+R...
**Toggle style inspector**: when clicked icon turns orange. Nothing else happens.
**Toggle x-ray mode**: Nothing happens when clicked.
**Toggle grid system guide**: Nothing happens when clicked.
**Toggle help panel**: Nothing happens when clicked.

There's also some sort of command line...what is this for? Are there any instructions?

**Comment by re-co** [comment]
For X-ray and Grid Guide you should manually add this CSS gist in stylesheets: 
[https://gist.github.com/re-co/18c7b776fbd20c6d3c1343c04792944c](url)

It is because you can easy config it's CSS according to yours needs.
You just add additional breakpoints using CSS and config grid guide using CSS variables for offset, gutter and columns

NOTE: help is for future implementation, and for now it does nothing but in future it should open help panel with config options.

Please read Wiki pages and suggest improvements to our documentation if it is confusing.

Refreash button - it is experimental feature, but there is better way than ctrl + r, you just save and it will trigger reload like VS Code Live Server.

**Comment by AnInfiniteNumberofMonkeys** [comment]
OK, I read the Wiki. This one (2.2, Launch Live Server and with every save, Live Server window will do autoreload). Doesn't work. After saving, the frontend in the new window does not auto-update. THis one: (2.4, View all applied styles to component id or class) also does not work.

**Comment by AnInfiniteNumberofMonkeys** [comment]
I also do not have access to this feature: 2.5 Viewport handles

**Comment by re-co** [comment]
Hmm I'll check `2.2`,

`About 2.4 `
Works 100% but anatomty is both easy and tricky. It is easy when you know where to look. But tricky of you don't.
On Right you have `Panelator` or side manager with four icons before to save button

![image](https://user-images.githubusercontent.com/77888923/124377672-65c82300-dcad-11eb-8e7b-16ed0209aab0.png)

In my case Structure Panel is opened, and when I make another click on Structure panel it wil hide that panel and you will be able to see Style Inspector window.

![image](https://user-images.githubusercontent.com/77888923/124377765-f30b7780-dcad-11eb-90a2-4183bce04ab4.png)

About `2.5 `
Same issue as `2.4`
![image](https://user-images.githubusercontent.com/77888923/124377805-38c84000-dcae-11eb-832b-74aca973d6aa.png)
![image](https://user-images.githubusercontent.com/77888923/124377836-67deb180-dcae-11eb-8f66-b7755404bc51.png)

When you see green dot in interface it indicates that certain option i active, but can be minimized.
You need minimize command-line to see handles so right-bottom corner dot should be orange.

**Comment by AnInfiniteNumberofMonkeys** [comment]
Re. 2.4: Still doesn't work for me. When I click the Structure panel button the structure panel just disappears and is replaced by a blank grey area.
<img width="177" alt="Screen Shot 2021-07-04 at 11 16 48 AM" src="https://user-images.githubusercontent.com/13838253/124395501-56e76d80-dcb9-11eb-8a75-4c164e77b2e9.png">

Re. 2.5 When I click the small green dot it changes to orange adn the entire bottom bar disappears, but no niewport handles appear.
<img width="1919" alt="Screen Shot 2021-07-04 at 11 18 03 AM" src="https://user-images.githubusercontent.com/13838253/124395528-839b8500-dcb9-11eb-8f31-d573159af9a2.png">

**Comment by re-co** [comment]
Again I can see there is EE I think active. I wrote same thing 5 times and again same thing happens.
So I am closing this issue becausue I'm not sure that is bug with native Oxygen.

Sorry but I feel really dumb to tell to every issue twice to disable 3rd party plugins and I don't know are you joking with me.
