### ISSUE TITLE
Issues with Oxygen Zoom value and viewport

### ISSUE THREAD

**Issue by cordschneider** [re-co/recoda-ws#24]
**Issue**
The Zoom value reflects the width of the contents relative to the width of the viewport. When a page has a Zoom value of 64% then the content width is 64% of the viewport width. The content is not expanded to fill 100% of the viewport width.

![image](https://user-images.githubusercontent.com/46093590/124477034-72c34000-dd9b-11eb-94c6-a8565a797fcb.png)

Clicking the 'lock' expands the contents to 100% of the viewport width.

![image](https://user-images.githubusercontent.com/46093590/124483581-67bfde00-dda2-11eb-80ea-0c5499f029c0.png)

Toggling the structure panel on and off seems to increase the amount of 'dead space' between the right side of the content and the structure panel.

![image](https://user-images.githubusercontent.com/46093590/124477111-88d10080-dd9b-11eb-9f1b-72314738e131.png)

**Expected**
The Zoom value reflects the width of the viewport page width relative to the width of the screen, expanding the content to fix 100% of the viewport. When a page has a Zoom value of 42%, it means that the width of the visible content has been reduced to 42% of its actual size.

![image](https://user-images.githubusercontent.com/46093590/124477173-9dad9400-dd9b-11eb-9044-04647fb64a98.png)

Clicking the 'lock' expands the contents to the actual size (i.e. 100%) often meaning that the contents are wider than the viewport and the user is required to scroll left and right.

![image](https://user-images.githubusercontent.com/46093590/124483395-347d4f00-dda2-11eb-809f-3861123f0493.png)

**Testing Environment**
Local 6.0.0+5444
WordPress: 5.7.2
Oxygen: 3.8
No other plugins

**Comment by re-co** [comment]
Big thanks, I have noticed this too but I'll look wrap this fix with new feature together with custom iframe controller:
You can see this feature idea: _https://github.com/re-co/recoda-ws/issues/12_


_Btw now I am in process of rewriting recoda-ws JS with global script which will be some sort of API for future, main purpose of this will be extract patterns so feature file should contain logic, and global script should be worried about certain tasks so code could be more readable and fixing repeting patterns could be done in one place_

**Comment by re-co** [comment]
Fixed in 0.9.0
