### ISSUE TITLE
OxyTools Navigator UI bug

### ISSUE THREAD

**Issue by demetre19** [re-co/recoda-ws#33]
When Oxy Toolbox Navigator function is on, there is an overlap.
(https://user-images.githubusercontent.com/29856708/125200417-6b75c800-e2ae-11eb-9ed5-b691c3509f3b.jpg)

Could you please add condition (if OXTB Navigator is on = then add 33px top margin to

#oxygen-ui .ct-panel-elements-managers, #oxygen-ui .oxygen-global-settings, #ct-viewport-container.oxy-fullscreen-toggle {
    margin-top: 33px;

![CleanShot 2021-07-12 at 01 11 55](https://user-images.githubusercontent.com/29856708/125200443-8a745a00-e2ae-11eb-85c4-8e53cb42f622.jpg)

**Comment by re-co** [comment]
Hmm I don't have that plugin.
Can you pleas provide css hook for that plugin, or if you don't know ask Mr. Katakam what is that and if you can tell me height value of that bar what is so my solution could be done via CSS varibles:
`.OXTB-navigator-active change my variables ` this solution could affect multiple tabs which I control via one variable.

**Comment by demetre19** [comment]
Solution using advanced scripts

![CleanShot 2021-07-14 at 02 22 59](https://user-images.githubusercontent.com/29856708/125489403-d73bdb0a-16f3-4f04-be9f-9e36cb57aaee.jpg)


Here is the code.
#oxygen-ui .ct-panel-elements-managers,
			#oxygen-ui .oxygen-global-settings,
			#ct-viewport-container.oxy-fullscreen-toggle {
				top: 90px;
				margin-top: 35px
			}

**Comment by re-co** [comment]
Added JS in 0.9.0 which should be universal hack for this and EE.
Script checks if there is offset between oxygen topbar and screen and adjust other via CSS variables so it should be universal fix.
