### ISSUE TITLE
Wrap on Xray

### ISSUE THREAD

**Issue by demetre19** [re-co/recoda-ws#34]
![CleanShot 2021-07-13 at 02 24 48](https://user-images.githubusercontent.com/29856708/125322887-941ac200-e381-11eb-992e-e96f39aac44d.jpg)
Small UI issue.

Needs Wrap on XRAY

**Comment by re-co** [comment]
I will turn ON codemirror wrap option

**Comment by re-co** [comment]
Implemented, coming in 0.9,0
I'm closing this issue.
