### ISSUE TITLE
Cycle Through Viewport Handles

### ISSUE THREAD

**Issue by demetre19** [re-co/recoda-ws#36]
[ FEATURE REQUEST ] 

It would be great to be able to cycle through the viewport handles using a shortcut, perhaps

SHIFT + COMMAND + ⟵ to go small
SHIFT + COMMAND + ⟶ to go bigger

**Comment by re-co** [comment]
Complexity from 1 to 10: 
I would say it's around  3.

I will add shortcuts they are they are DOM sibelings so with jQuery should be really easy.
Only tricky thing which can be i need to try in console, which handle is active.

I will try to add in 0.9

**Comment by re-co** [comment]
Implemented in 0.9.0
